Fa206 multi select
ctc-oss/fapolicy-analyzer pull request #360
Opened 2021-12-21 19:49 UTC by egbicker

2021-12-22 11:57 UTC, dorschs57 requested changes

2021-12-22 11:57 UTC, dorschs57 commented on fapolicy_analyzer/ui/ancillary_trust_database_admin.py
> +        self.selectedFile = trusts if trusts else None
```suggestion
        self.selectedFiles = [t.path for t in trusts] if trusts else None
```

2021-12-22 11:57 UTC, dorschs57 commented on fapolicy_analyzer/ui/ancillary_trust_database_admin.py
> +            if trust:
I'm not sure why you need to loop here.  We can only display 1 file at a time in the details, so you should just pull either the first or last one off the list to display to make this more efficient.

2021-12-22 11:57 UTC, dorschs57 commented on fapolicy_analyzer/ui/policy_rules_admin_page.py
> +            uids = [None]
```suggestion
         uids = [datum[1] for datum in data] if data else [None]
```

2021-12-22 11:57 UTC, dorschs57 commented on fapolicy_analyzer/ui/policy_rules_admin_page.py
> +    def on_file_selection_changed(self, secondaryAction, data):
I think keeping this as `on_subject_selection_changed` makes it more clear what it is used for.

2021-12-22 11:57 UTC, dorschs57 commented on fapolicy_analyzer/ui/searchable_list.py
> +            data = []
```suggestion
        data = [model[i] for i in treeiter] if model and treeiter else []
```

2021-12-22 11:57 UTC, dorschs57 commented on fapolicy_analyzer/ui/subject_list.py
> +            self.file_selection_changed(None)
```suggestion
        fileObjs = [datum[3] for datum in data] if data else None
        self.file_selection_changed(fileObj)
```

2021-12-22 11:57 UTC, dorschs57 commented on fapolicy_analyzer/ui/system_trust_database_admin.py
> +            trust = trusts[-1]
👍

2021-12-22 11:57 UTC, dorschs57 commented on fapolicy_analyzer/ui/trust_file_list.py
> +            trust = None
```suggestion
        trust = [datum[3] for datum in data] if data else None
```

2021-12-22 12:11 UTC, dorschs57 commented
I'm seeing an error `NoneType object is not iterable` when I multiselect or single select a file from the System Trust Database Admin screen and click Add to Ancillary Trust button.

2021-12-22 12:19 UTC, dorschs57 commented
> I'm seeing an error `NoneType object is not iterable` when I multiselect or single select a file from the System Trust Database Admin screen and click Add to Ancillary Trust button.

I see the same thing on the Ancillary Trust Database Admin screen when I attempt to trust/untrust files.

2021-12-22 17:51 UTC, egbicker commented
Fixed the `NoneType object is not iterable` issue and all the code changes you mentioned

2021-12-23 13:20 UTC, dorschs57 requested changes

2021-12-23 13:20 UTC, dorschs57 commented on fapolicy_analyzer/ui/policy_rules_admin_page.py
> +                secondaryAction()
Much like on the ATDA, you are wasting cycles by looping over the list here.  We are only displaying the last selected users data.  In fact allowing multiselect on the users and groups is pointless as it is right now.  The user can only act on the last selected user.  Are there plans to merge the lists from multi users/groups for the secondary action?

2021-12-23 13:20 UTC, dorschs57 commented on fapolicy_analyzer/ui/policy_rules_admin_page.py
> +                secondaryAction()
See my comment above on the `on_user_selection_changed` method.

2021-12-23 13:20 UTC, dorschs57 commented on fapolicy_analyzer/ui/system_trust_database_admin.py
> +                self.file_added_to_ancillary_trust(sfile.path)
These files should be added in a single changeset, so you'll have to update the `file_added_to_ancillary_trust` event and associated handler to handle multiple file paths as an argument.  Similar to my comment from the add/delete trust in the ATDA file.

2021-12-23 13:37 UTC, dorschs57 commented
Here are just some general comments on this:

1. The code in the system and ancillary trust database admin pages should be smart enough that I’m not creating a changeset for a file that doesn’t actually change its trust status. For example right now I can multiselect a mixture of trusted and untrusted files. My options on which button (Trust or Untrust) that is active is dictated by the last selected file. If the last file selected was untrusted, I can untrust the whole set of selected file. This means I’m generating changesets to untrust files that are already untrusted. My suggestion would be to only allow an action to take place if all the selected files have the same status. i.e. if they are all untrusted the Trust button is active, if they are all trusted the Untrust button is active, and if they are mixed both button are disabled. Apply similar logic to the system trust page and the Add to Ancillary Trust button.

2. Multiselect on the Policy Analysis page is useless at this point. We can only display data for a single selected item, and the only action, Reconciliation, doesn’t allow for multi select. Here my suggestions. Eliminate the multiselect on the users and groups. There is no actions that can be taken on them right now and merging multiple users/groups subject list together seems complicated. I don’t know that we want to do that. We can keep the multiselect on subjects and objects lists for now with the idea of the reconciliation wizard to come down the road. I created issue #364 for this.

2021-12-23 14:29 UTC, dorschs57 commented
> 2. Multiselect on the Policy Analysis page is useless at this point. We can only display data for a single selected item, and the only action, Reconciliation, doesn’t allow for multi select. Here my suggestions. Eliminate the multiselect on the users and groups. There is no actions that can be taken on them right now and merging multiple users/groups subject list together seems complicated. I don’t know that we want to do that. We can keep the multiselect on subjects and objects lists for now with the idea of the reconciliation wizard to come down the road. I created issue Policy Analysis Reconciliation Wizard #364 for this.

After talking with @jw3 I'll amend this a bit.  I'd still get rid of multiselect on users and groups.  On the subjects and objects for this PR:
1. If the user single selects and right-clicks, keep as is with the Reconcile option
2. If the user multi-selects and right-clicks, remove the Reconcile option from the context menu and replace it with an option to Trust or Untrust (depending on the trust status of the selected files).  If the user selects Trust/Untrust, show a simple `Yes/No` dialog to confirm and then generate a changeset for all selected items. This would be more of a "bulk action" compared to a wizard.  Once #364 is in place we can swap it out for that.

2022-01-04 16:30 UTC, jw3 commented
Change the text of the button on the System Trust tab to be "Add To Ancillary Trust Database", rather than picking singular or plural version of "Files"

2022-01-06 19:06 UTC, dorschs57 requested changes

2022-01-06 19:29 UTC, egbicker commented on fapolicy_analyzer/ui/system_trust_database_admin.py
> +            for trust in trusts:
You're right. I thought this was doing more than just displaying which is why I left it in. Same for the ancillary one.

2022-01-06 21:57 UTC, egbicker commented on fapolicy_analyzer/ui/subject_list.py
> +                self.fileChangeContextMenu.popup_at_pointer()
I like your fix. The other option would be to have a "Trust status mismatch" menu option pop up instead and have it do nothing but provide info.

2022-01-12 11:46 UTC, dorschs57 commented on fapolicy_analyzer/ui/subject_list.py
> +    def find_db_trust(self, subject):
Make this a "private" method by using the double underscore prefix.

2022-01-12 11:59 UTC, dorschs57 commented on fapolicy_analyzer/ui/subject_list.py
> +                changeset.add_trust(*paths)
I still don't think you logic is quite right here.  Not that you have the trust you need to look at the `trust.status` to determine the action.
* `trust` is None = Add
* `trust` is `t` and `subject.trust` is `st` = no action (there is nothing we can change about a file trusted in the system db)
* `trust` is `t` and `subject.trust` is `at` = Del
* `trust` is not `t` = Add

You can look at `TrustReconciliationDialog.__load_details` for how I'm setting the button visibility for this.

2022-01-12 12:38 UTC, dorschs57 requested changes

2022-01-12 12:38 UTC, dorschs57 commented on fapolicy_analyzer/ui/subject_list.py
> +                changeset.add_trust(*paths)
I still don't think you logic is quite right here. Not that you have the trust you need to look at the trust.status to determine the action.

trust is None = Add
trust is t and subject.trust is st = no action (there is nothing we can change about a file trusted in the system db)
trust is t and subject.trust is at = Del
trust is not t = Add
You can look at TrustReconciliationDialog.__load_details for how I'm setting the button visibility for this.

2022-01-12 12:38 UTC, dorschs57 commented on fapolicy_analyzer/ui/subject_list.py
> +        trust = self.find_db_trust(subjects[0])
I think here you want to loop over all the subjects and add them to the `Changeset` right?

2022-01-12 12:38 UTC, dorschs57 commented on fapolicy_analyzer/ui/subject_list.py
> +                    self.fileChangeContextMenu.append(self.fileChangeContextMenu.trustItem)
Similar to up in line 169, you need to use both the `subject.trust` and the `dbtrust.status` values here to determine what menu option to show.

2022-01-12 12:38 UTC, dorschs57 commented on fapolicy_analyzer/ui/subject_list.py
> +                )
This logic is harder than I was first thinking, and this isn't going to work.  You need to but some logic in to determine the  list of actions (trust or untrust) based on both the `subject.trust` (AT, ST, U) and the `dbtrust.status` (T, D).  Then check if all the actions are the same.  If not, exit out without giving the user to any menu options.

2022-01-19 13:42 UTC, dorschs57 commented
I submitted a couple easy fixes from my testing. 
1. I lowered the min GTK version on the confirm dialog to 3.22.  This is the version we use everywhere.
2. I returned `True` from the right-click handler of the `subjectList`.  This stops the event cascading so when you have multiple files selected and right-click it keeps all the files selected.

2022-01-19 14:03 UTC, dorschs57 requested changes
I'm seeing some issues with files trusted in the system trust database. I'm testing with the `fapolicy-analyzer/tests/data/events0.log` file. 
1. Select `bin` user
2. Multiselect `/usr/bin/find` and `/usr/bin/gzip`
3. Right-click and I'm presented with the `Untrust Files` option even though both are trusted in the system trust db. (issue 1)
4. Select `Untrust Files` and the confirm dialog says `2 files will be trusted. Trust selected files?` even though the option was to Untrust the files. (issue 2)
5. Click `Yes` to confirm and it appears to create an empty changeset. (issue3)

2022-01-21 16:57 UTC, merged