465 analysis time selection
ctc-oss/fapolicy-analyzer pull request #665
Opened 2022-11-17 16:58 UTC by egbicker

2022-11-23 12:38 UTC, dorschs57 requested changes

2022-11-23 12:38 UTC, dorschs57 commented on fapolicy_analyzer/tests/test_time_select_dialog.py
> +    assert widget.get_object("stopMinute").get_sensitive() is False
I'd like to see some testing of the `TimeSelectDialog.get_time` funciton. The function has a lot of edge cases where you are trapping exceptions and showing an error message that should be tested.

2022-11-23 12:38 UTC, dorschs57 commented on fapolicy_analyzer/ui/strings.py
> +TIME_SELECTION_STOP_INVALID = _("Selected Stop Time is not a valid date")
You'll need to run the `extract_messages` script an commit the updated .pot file with the new strings.

2022-11-23 12:52 UTC, jw3 commented
I ran through this.  Some comments below on the UI, which looks like this on el8

![image](https://user-images.githubusercontent.com/1545372/203549031-288db21b-c8b6-47a1-9eae-7a27e96b1af1.png)

1. PR needs a description.
2. The "Select" button always results in a time range around the current time, regardless of whether I previously selected something.
3. Selecting a time range does not appear to change the display.  Is this working for anyone else?
4. There is some white space at the top of the dialog
5. Title of the dialog needs set

2022-11-23 12:58 UTC, jw3 commented
@egbicker 

After seeing this in action I wonder if the selection should be simpler.  What if we trim this down to a "Show events over the past X unit-of-time

So instead of picking a start _and_ stop time, just pick a start time by entering some number and selecting the unit from a drop down, eg
  - 1 hours
  - 5 minutes
  - 3 days

Some simple math to figure the seconds in whatever is selected and subtract that from time.time() and set it on the bindings, refresh the view.

We can default this to show the last hour.

The display when not in the UI can just render a string that says something like "Showing events from the last X units".  This label could event fit in the status bar, I think we talked about that option at some point, but that could also be done later if that is not very easy right now.

The button to bring up the dialog to pick the time could be moved to the toolbar.

2022-11-29 09:21 UTC, jw3 requested changes
## Showing Syslog
![image](https://user-images.githubusercontent.com/1545372/204487942-5eadd832-9ac4-4229-bc25-c801f1c3d3a2.png)
- Change "Delay" to "Showing events since"
- Can the "Select" button move to the toolbar and have a clock icon?

## Showing Debug log
![image](https://user-images.githubusercontent.com/1545372/204488917-e3f2ff7e-38d1-45c1-865b-5c3d21459669.png)
- After seeing it in action, hiding the widget rather than disabling seems appropriate. 

## Selecting a time
![image](https://user-images.githubusercontent.com/1545372/204487564-1df8f9b5-84d3-49bb-9a94-547d48b0c449.png)
- remove the + and - buttons, just a text entry that accepts numbers

2022-11-29 16:46 UTC, egbicker commented
@jw3 Got those changes taken care of and tests updated

2022-11-29 17:50 UTC, jw3 commented
> @jw3 Got those changes taken care of and tests updated

Looks better, though it doesn't seem to be working for me.  What platform are you testing the gui on?

2022-11-29 18:37 UTC, egbicker commented
Fedora but I think I might have messed something up when I was jumping back in. Mind if I give you a call?

2022-11-29 22:20 UTC, egbicker commented
Figured out the timing issue. Looks like there was a timezone issue getting in the way of correct timings

2022-11-30 20:59 UTC, jw3 commented
@egbicker  looking better filtering appears to work.  I got into a weird state like this by making a selection from the subject column and then filtering in a way that eliminates that subject.

![image](https://user-images.githubusercontent.com/1545372/204906514-e24a9fb6-9a6d-4002-a7f7-4383396c8c03.png)


Also one more thing is that the previous time that was selected should be preserved in the dialog when you open it again.

2022-11-30 22:30 UTC, egbicker commented
Got the persistent data stuff working. Noticed that issue this morning, haven't gotten it working yet

2022-12-01 03:16 UTC, egbicker commented
@jw3 I think I fixed the issue we were seeing with the subjects not clearing.

2022-12-01 11:21 UTC, jw3 commented
All good, just one nit.

![image](https://user-images.githubusercontent.com/1545372/205038840-61409b3b-c716-4166-a911-565ceec21bfa.png)

Get rid of the read-only text field, just include the duration text in the label with the static text.

2022-12-01 12:15 UTC, dorschs57 requested changes

2022-12-01 12:15 UTC, dorschs57 commented on fapolicy_analyzer/ui/policy_rules_admin_page.py
> +        self.time_number = 1
These should probably be made "private" with the double underscore in front.

2022-12-01 12:15 UTC, dorschs57 commented on fapolicy_analyzer/ui/policy_rules_admin_page.py
> +        time_number = int(time_dialog.get_object("timeEntryField").get_buffer().get_text())
You could simplify a lot of this code in here if the `TimeSelectDialog` implemented getters and setters for `active_id` and `text` that hide all the implementation details.

2022-12-01 12:15 UTC, dorschs57 commented on fapolicy_analyzer/ui/policy_rules_admin_page.py
> +                self.__log.begin(int(time.time()) + tzdelta - self.time_delay)
Can you add a test to hit this branch?

2022-12-01 12:15 UTC, dorschs57 commented on fapolicy_analyzer/ui/policy_rules_admin_page.py
> +            display_unit = "Day"
These branches are not tested either.

2022-12-01 17:21 UTC, jw3 approved these changes
Looks good to me.  I'll watch for @dorschs57 approval and then merge.

2022-12-01 21:08 UTC, dorschs57 approved these changes

2022-12-02 12:36 UTC, merged