Slow filter on system trust search
ctc-oss/fapolicy-analyzer pull request #738
Opened 2023-01-16 20:24 UTC by egbicker

Changing search bar behavior to only begin filtering when `Enter` key is pressed instead of upon key press

2023-01-17 12:18 UTC, dorschs57 requested changes
Here is what I'm seeing on my system. When I type in the search box nothing happens, as expected. However when I hit enter after typing nothing happens either. I put some print statements in before the if condition on line 161 and the event key value when I hit enter is  65293. It's comparing it to the value 16777215 so nothing happens. Also when I hit enter from my number pad its a different value. Can we use the `activate` signal from the `Entry` widget instead of the `key_press` event? After a quick search online that seems to be the suggested method for how to capture an enter key from an `Entry`.

Second problem is when I type and then click the X icon to clear it, my application completely locks up to the point that I have to force close it. The text is never cleared from the search box and my application becomes completely unusable.

2023-01-17 12:18 UTC, dorschs57 commented on fapolicy_analyzer/ui/searchable_list.py
>          self._update_tree_count(self.__get_tree_count())
To DRY this code up a bit, make a private method called `__refilter` or something and have both handlers call it.

2023-01-17 16:17 UTC, egbicker commented
The activate is a good call. The X icon was causing me to have some unresponsive behavior prior to this branch too. If I let it sit and don't close the application, it will eventually clear the search bar.

2023-01-17 17:03 UTC, jw3 commented
If there is something strange with the button and it can be removed/hidden, that would be acceptable.  A button to clear a single field is of minimal value

2023-01-17 21:41 UTC, egbicker commented
The only way I could find to remove the "clear" icon didn't seem to work before the user began inputting text, so now its getting drawn and erased on each keystroke which I don't like. Not sure what the best option here is

2023-01-18 12:12 UTC, dorschs57 commented
> The only way I could find to remove the "clear" icon didn't seem to work before the user began inputting text, so now its getting drawn and erased on each keystroke which I don't like. Not sure what the best option here is

Have you tried the `icon_release` signal instead of the icon press? Its also possible things are logging up because the built in functionality of the clear button is also kicking in at the same time. You can try stopping event propagation by returning a `True` from you handler I think. You might have to handle both the press and release signals to stop propagation in both places.

2023-01-19 21:01 UTC, egbicker commented
@dorschs57 suggestion to change `SearchEntry` to `Entry` removed the clear button. Now the user must backspace and hit enter again to revert to the full trust database display. Working on the test to simulate an enter key programmatically now.

2023-01-25 20:10 UTC, dorschs57 commented
@egbicker @jw3 I'm seeing some better performance from the filtering with my changes for async trust loading. Its limited testing right now, but it might be work holding off for my work on #711.

2023-02-14 12:27 UTC, jw3 commented
@egbicker conflicts after #750

2023-02-14 16:22 UTC, egbicker commented
@jw3 I'm seeing an issue with the new "check_ancillary_trust" with `(left != right)`

2023-02-15 13:43 UTC, jw3 commented
@egbicker Did something happen when you resolved conflicts?  I see only one line changed in this PR.

Assuming this branch is broken, I took from the previous commit and rebased on master to test.  Saw seemingly sane behavior.

List the steps to repro the error and Ill test again.

2023-02-15 14:45 UTC, egbicker commented
@jw3 I'm seeing this in my master branch, looks like one of the checks in the rust backend doesn't like what I have going. I was behind on syncing my fork so I just got that update.

2023-03-02 16:34 UTC, jw3 approved these changes
Tested this locally, looks good :+1: 

Our search is slow in general.  Need to address this, but not here.

2023-03-02 16:46 UTC, merged