Customizable initial application view loading from the config file
ctc-oss/fapolicy-analyzer pull request #789
Opened 2023-02-23 18:58 UTC by dorschs57

2023-03-02 18:04 UTC, jw3 reviewed
Will need to add a `Requires:      python3-toml` to both spec files

2023-03-07 20:05 UTC, dorschs57 commented
@tparchambault Can you give the session saving and reloading a spin on this branch. I created a reusable widget to generate a file chooser dialog and switched all the places we were repeating ourselves in the code over to use it. The session management stuff used it in 3 different places.

2023-03-07 23:01 UTC, jw3 commented
@dorschs57 this picked up a conflict from master

2023-03-09 19:10 UTC, dorschs57 commented
@jw3 I put that minor change in to remove the + buttons.

2023-03-09 19:30 UTC, jw3 commented on fapolicy_analyzer/ui/features/system_feature.py
> -        print(check_ancillary_trust)
:+1:

2023-03-10 10:16 UTC, jw3 commented on fapolicy_analyzer/ui/types.py
> +    ANALYZE_FROM_AUDIT = "audit log"
This should be "debug log".

We have had some ambiguity between debug/audit in the past.  It doesnt need fixed now other than what is user facing here.

We updated the other user facing part in #771

2023-03-10 10:20 UTC, jw3 requested changes
Just the one comment on the /audit/debug/ replacement, otherwise :+1:

I tested all view configurations, including not present.  Also clicked through saving and loading sessions and a debug log.

2023-03-10 15:38 UTC, jw3 commented on fapolicy_analyzer/ui/types.py
> +    ANALYZE_FROM_AUDIT = "audit log"
@dorschs57 I did a /audit/debug/ for this

2023-03-10 15:49 UTC, jw3 commented
@tparchambault any comment on this one?  I tested the pickers for the session operations, seemed to be in order.

2023-03-10 16:57 UTC, dorschs57 reviewed
@jw I'm good with your last commit. That was exactly what I had planned to do. If you tested it 👍

2023-03-10 16:57 UTC, dorschs57 commented on fapolicy_analyzer/ui/types.py
> +    ANALYZE_FROM_DEBUG = "debug log"
👍

2023-03-10 17:55 UTC, tparchambault commented
Currently reviewing it...

Can the generated toml file contain a comment with the possible valid choices for the option? Not this PR but downstream...

> The possible values are "trust", "rules", "audit log", "syslog", or "profiler".

2023-03-10 18:09 UTC, jw3 commented
> Can the generated toml file contain a comment with the possible valid choices for the option? Not this PR but downstream...

It could.  Though the comment in an existing config would be inaccurate if we add a new view.

User guide is probably the place for it. There is a section there now describing it.

2023-03-10 18:22 UTC, tparchambault commented
Are we adding an additional `*.toml` file or renaming the existing `fapolicy-analyzer.toml` to `config.toml`? I'm hoping the latter.

2023-03-10 20:01 UTC, tparchambault commented
Independent of our tool but something we need to be aware of, as something @jw3 also wrestled with yesterday:

> Mar 10 14:48:58 son-o-wimpy dbus-daemon[898]: [system] Successfully activated service 'org.fedoraproject.SetroubleshootPrivileged'
Mar 10 14:49:00 son-o-wimpy setroubleshoot[4401]: SELinux is preventing fapolicyd from write access on the file fapolicyd.pid. For complete SELinux messages run: sealert -l c719e1c0-b6e1-462a-b40f-ccbb8ba66612
Mar 10 14:49:00 son-o-wimpy setroubleshoot[4401]: SELinux is preventing fapolicyd from write access on the file fapolicyd.pid.
                                                  
Over RHEL8.6 via an RPM install, I was testing control of `fapolicyd` from `fapolicy-analyzer`.

2023-03-10 20:15 UTC, tparchambault commented
Only one anomaly observed and I'm assuming it's independent of this PR: After `Deploying Changesets` and allowing the `Accept these changes?` count-down dialog to expire, which initiated an automatic Trust rollback, the previous pre-deployment session state was not reloaded or at least visible in the Ancillary Trust view, (which by itself is neither good nor bad, just a design choice), however the application state remained in the `pending changes` such that attempts to quit were met with the `You have applied changes` dialog. This may be a known issue.

2023-03-10 20:31 UTC, merged

2023-03-10 22:17 UTC, tparchambault reviewed
Tested over Rhel86. All good. No source comments that rise above the six of one, half dozen of another syntax and naming level. Redox and async is the future.